"""
Eventos considerados «importantes» para o nudge proativo 12h antes.

Quando o cliente regista um evento na agenda e NÃO pede lembrete, se o evento
estiver nesta lista enviamos um lembrete «surpresa» 12h antes, com mensagem
simpática/marota. Esse lembrete não aparece na lista (/lembrete) — é uma surpresa.

Cada linha é um grupo de sinónimos/variantes em pt-BR, pt-PT, es, en.
Total: 500 grupos (eventos). Matching: evento do user (lower) contém alguma destas strings.
"""

# 500 eventos importantes: listas de keywords por "tipo" (qualquer idioma)
# is_important_event_for_nudge() verifica se o nome do evento contém alguma keyword
PROACTIVE_NUDGE_EVENT_KEYWORDS: list[list[str]] = [
    # 1-50: Saúde e consultas
    ["consulta", "médico", "medico", "doctor", "appointment", "cita", "clínica", "clinica", "hospital"],
    ["dentista", "dentist", "dental", "odontólogo", "odontologo", "odontología", "dentista"],
    ["exame", "exames", "examen", "exam", "test", "análise", "analise", "blood test", "exame de sangue"],
    ["vacina", "vacinação", "vacinacao", "vaccine", "vacunación", "vacuna", "dose", "vaccination"],
    ["fisioterapia", "fisioterapeuta", "physiotherapy", "physical therapy", "fisioterapia"],
    ["psicólogo", "psicologo", "psicóloga", "psicologa", "psychologist", "therapist", "terapia", "therapy"],
    ["oftalmologista", "oculista", "optometrista", "ophthalmologist", "eye doctor", "oftalmólogo"],
    ["cardiologista", "cardiólogo", "cardiologist", "cardiólogo", "heart"],
    ["dermatologista", "dermatólogo", "dermatologist", "skin", "pele"],
    ["ginecologista", "ginecólogo", "gynaecologist", "obstetra", "obstetrician"],
    ["pediatra", "pediatrician", "pediatra", "child doctor"],
    ["cirurgia", "surgery", "operación", "operacao", "operação", "surgical"],
    ["ressonância", "ressonancia", "mri", "resonancia", "ultrassom", "ultra-som", "ultrasound"],
    ["radiografia", "raio-x", "raio x", "x-ray", "radiografía"],
    ["retirada de resultado", "resultado de exame", "lab results", "resultados"],
    ["nutricionista", "nutrição", "nutricao", "dietitian", "nutritionist", "nutrición"],
    ["acupuntura", "acupuncture", "acupuntura"],
    ["massagem", "massage", "masaje", "massagem agendada"],
    ["sessão de terapia", "sessao de terapia", "therapy session", "sesión de terapia"],
    ["medicina alternativa", "alternative medicine", "medicina natural"],
    ["check-up", "checkup", "revisão de saúde", "revisao de saude", "health check"],
    ["doação de sangue", "doacao de sangue", "blood donation", "donación de sangre"],
    ["transplante", "transplant", "transplante"],
    ["quimioterapia", "chemotherapy", "quimioterapia"],
    ["radioterapia", "radiotherapy", "radioterapia"],
    ["emergência médica", "emergencia medica", "medical emergency", "urgencia"],
    ["pronto-socorro", "emergency room", "urgencias", "er"],
    ["farmácia", "farmacia", "pharmacy", "buscar remédio", "buscar remedio", "retirar medicamento"],
    ["consulta de acompanhamento", "follow-up", "follow up", "controle", "control"],
    ["avaliação médica", "avaliacao medica", "medical evaluation", "evaluación médica"],
    ["consulta pré-natal", "consulta pre-natal", "prenatal", "prénatal", "gravidez", "pregnancy"],
    ["parto", "birth", "nacimiento", "dar à luz", "dar a luz"],
    ["triagem", "triage", "triaje"],
    ["curativo", "dressing", "bandagem", "bandage"],
    ["inalação", "inalacao", "inhalation", "nebulização", "nebulizacao"],
    ["sutura", "suture", "pontos", "stitches"],
    ["consulta veterinário", "veterinário", "veterinario", "vet", "pet doctor", "mascota"],
    ["vacina do pet", "vacina do cão", "vacina do cao", "pet vaccination"],
    ["castração", "castracao", "neutering", "esterilización"],
    ["banho e tosa", "grooming", "peluqueria canina"],
    ["internação", "internacao", "hospitalization", "ingreso"],
    ["alta hospitalar", "hospital discharge", "alta"],
    ["consulta de rotina", "routine check", "revisão anual", "revisao anual"],
    ["retorno", "return visit", "consulta de retorno"],
    ["segunda opinião", "second opinion", "segunda opinión"],
    ["laudo", "medical report", "informe médico", "resultado"],
    ["autorização médica", "autorizacao medica", "medical clearance"],
    ["receita", "prescription", "receta", "receita médica"],
    ["consulta online", "telemedicina", "telemedicine", "consulta remota"],
    ["atestado", "sick note", "baja médica", "medical certificate"],
    ["limpeza de pele", "facial", "limpieza facial", "skin cleaning"],
    ["depilação", "depilacao", "waxing", "depilación"],
    ["manicure", "pedicure", "unhas", "nails", "uñas"],
    # 51-120: Trabalho e reuniões
    ["reunião", "reuniao", "reuniões", "reunioes", "meeting", "meetings", "reunión"],
    ["apresentação", "apresentacao", "presentation", "presentación", "presentación"],
    ["entrevista", "entrevistas", "interview", "job interview", "entrevista de emprego", "entrevista de trabajo"],
    ["conferência", "conferencia", "conference", "conferencia"],
    ["palestra", "palestras", "talk", "charla", "lecture"],
    ["workshop", "workshops", "taller", "talleres"],
    ["seminário", "seminario", "seminarios", "seminario", "seminars"],
    ["webinar", "webinars", "seminário online", "seminario online"],
    ["videoconferência", "videoconferencia", "videoconference", "videollamada", "video call"],
    ["zoom", "teams", "google meet", "meet", "chamada de vídeo", "chamada de video"],
    ["daily", "standup", "stand-up", "daily standup"],
    ["retrospectiva", "retrospective", "retrospectiva"],
    ["planning", "planning meeting", "planejamento", "planificación"],
    ["sprint", "sprint planning", "sprint review"],
    ["one-on-one", "1:1", "one to one", "reunião individual", "reuniao individual"],
    ["reunião com cliente", "reuniao com cliente", "client meeting", "reunión con cliente"],
    ["reunião com chefe", "reuniao com chefe", "meeting with boss", "reunión con jefe"],
    ["brainstorm", "brainstorming", "lluvia de ideas"],
    ["kickoff", "kick-off", "kick off", "início do projeto", "inicio del proyecto"],
    ["entrega de projeto", "entrega de projeto", "project delivery", "entrega del proyecto"],
    ["deadline", "prazo", "prazo de entrega", "fecha límite"],
    ["demo", "demonstração", "demonstracao", "demonstration", "demostración"],
    ["pitch", "pitch presentation", "pitch de vendas"],
    ["negociação", "negociacao", "negotiation", "negociación"],
    ["fechamento de contrato", "closing", "fechar contrato", "cierre de contrato"],
    ["assinatura de contrato", "contract signing", "firma de contrato", "assinar contrato"],
    ["onboarding", "integração", "integracao", "incorporación"],
    ["avaliação de desempenho", "avaliacao de desempenho", "performance review", "evaluación de desempeno"],
    ["feedback", "sessão de feedback", "sesión de feedback"],
    ["treinamento", "treinamento", "training", "capacitación", "formación"],
    ["curso corporativo", "corporate training", "curso de empresa"],
    ["certificação", "certificacao", "certification", "certificación"],
    ["exame de certificação", "certification exam", "examen de certificación"],
    ["conferência de imprensa", "conferencia de imprensa", "press conference"],
    ["lançamento", "lancamento", "launch", "lanzamiento"],
    ["evento corporativo", "corporate event", "evento de empresa"],
    ["networking", "networking event", "evento de networking"],
    ["feira", "fair", "feria", "trade show", "exposição comercial", "exposicao comercial"],
    ["congresso", "congress", "congreso", "convención"],
    ["simpósio", "simposio", "symposium", "simposio"],
    ["mesa redonda", "round table", "mesa redonda"],
    ["auditoria", "audit", "auditoría", "auditoria"],
    ["inspeção", "inspecao", "inspection", "inspección"],
    ["vistoria", "vistorias", "vistoria"],
    ["entrega de relatório", "entrega de relatorio", "report delivery", "entrega de informe"],
    ["apresentação de resultados", "apresentacao de resultados", "results presentation"],
    ["reunião de equipe", "reuniao de equipe", "team meeting", "reunión de equipo"],
    ["reunião de diretoria", "reuniao de diretoria", "board meeting", "reunión de junta"],
    ["reunião de condomínio", "reuniao de condominio", "condo meeting", "reunión de condominio"],
    ["assembleia", "assembleia de condomínio", "assembly", "asamblea"],
    ["eleição", "eleicao", "election", "votación", "votação"],
    ["entrevista de saída", "entrevista de saida", "exit interview"],
    ["integração de novo colaborador", "onboarding", "incorporación"],
    ["desligamento", "desligamento", "offboarding", "baja"],
    ["proposta comercial", "proposta comercial", "commercial proposal", "propuesta comercial"],
    ["orçamento", "orcamento", "quote", "budget", "presupuesto"],
    ["apresentação de projeto", "apresentacao de projeto", "project presentation"],
    ["status report", "relatório de status", "relatorio de status", "informe de estado"],
    ["review de código", "review de codigo", "code review"],
    ["deploy", "deployment", "implantação", "implantacao"],
    ["go-live", "go live", "lançamento em produção", "lanzamiento"],
    ["incidente", "incident", "incidente crítico", "incidente critico"],
    ["post-mortem", "postmortem", "análise de incidente", "analise de incidente"],
    ["call de suporte", "support call", "llamada de soporte"],
    ["escalação", "escalacao", "escalation", "escalamiento"],
    ["handover", "passagem de turno", "entrega de turno", "traspaso"],
    ["reunião de pais", "reuniao de pais", "parent teacher", "reunión de padres"],
    ["reunião de pais e mestres", "parent teacher conference"],
    # 121-200: Viagens e transportes
    ["voo", "voos", "flight", "flights", "vuelo", "vuelos"],
    ["embarque", "boarding", "embarque"],
    ["check-in", "checkin", "check in", "facturación"],
    ["aeroporto", "airport", "aeropuerto"],
    ["partida", "departure", "salida", "partida do voo"],
    ["chegada", "arrival", "llegada"],
    ["conexão", "conexao", "connection", "escala", "layover"],
    ["trem", "comboio", "comboios", "train", "tren", "trenes"],
    ["ônibus", "onibus", "autocarro", "bus", "autobús"],
    ["metrô", "metro", "subway", "metropolitano", "último metro", "ultimo metro"],
    ["barco", "ferry", "barca", "ferryboat"],
    ["transfer", "transfers", "translado", "translados", "pickup"],
    ["aluguel de carro", "rent a car", "alquiler de coche", "car rental"],
    ["devolução do carro", "devolucao do carro", "car return", "devolución del coche"],
    ["viagem", "viagens", "trip", "trips", "viaje", "viajes"],
    ["reserva", "booking", "reservación", "reserva de hotel"],
    ["hotel", "check-in hotel", "checkin hotel"],
    ["passaporte", "passport", "pasaporte"],
    ["visto", "visa", "visado"],
    ["consulado", "consulate", "consulado"],
    ["embaixada", "embassy", "embajada"],
    ["seguro de viagem", "travel insurance", "seguro de viaje"],
    ["câmbio", "cambio", "exchange", "casa de câmbio"],
    ["bilhete", "bilhetes", "ticket", "tickets", "entrada", "entradas"],
    ["bilhete de avião", "bilhete de aviao", "plane ticket", "billete de avión"],
    ["bilhete de trem", "train ticket", "billete de tren"],
    ["estação", "estacao", "station", "estación"],
    ["porto", "port", "puerto", "aeroporto"],
    ["taxi", "táxi", "uber", "cab", "rideshare"],
    ["carro agendado", "scheduled car", "coche reservado"],
    ["viagem a trabalho", "business trip", "viaje de negocios"],
    ["férias", "ferias", "vacation", "vacaciones", "holiday"],
    ["lua de mel", "honeymoon", "luna de miel"],
    ["retorno de viagem", "return from trip", "regreso de viaje"],
    ["despedida no aeroporto", "airport goodbye"],
    ["recepção no aeroporto", "airport pickup", "recogida en aeropuerto"],
    ["bagagem", "baggage", "equipaje", "malas"],
    ["franquia de bagagem", "baggage allowance"],
    ["pré-bordo", "pre-bordo", "pre boarding"],
    ["portão", "portao", "gate", "puerta de embarque"],
    ["cartão de embarque", "cartao de embarque", "boarding pass", "tarjeta de embarque"],
    ["documentação de viagem", "documentacion de viagem", "travel documents"],
    ["teste covid", "covid test", "teste de viagem", "prueba covid"],
    ["autorização de viagem", "travel authorization"],
    ["reembolso de voo", "flight refund", "reembolso"],
    ["remarcação", "remarcacao", "reschedule", "reagendamiento"],
    ["upgrade", "upgrade de classe", "clase ejecutiva"],
    ["milhas", "miles", "pontos", "points", "fidelidade"],
    ["expiração de milhas", "expiration of miles"],
    ["renovação de passaporte", "renovacao de passaporte", "passport renewal"],
    ["visto de trabalho", "work visa", "visa de trabajo"],
    ["visto de estudante", "student visa", "visa de estudiante"],
    ["schengen", "schengen visa", "visado schengen"],
    ["vacinação para viagem", "travel vaccination", "vacunas para viajar"],
    ["consulta do viajante", "travel clinic", "consulta del viajero"],
    # 201-280: Educação e provas
    ["prova", "provas", "exam", "exams", "examen", "exámenes"],
    ["teste", "test", "test", "prueba"],
    ["avaliação", "avaliacao", "assessment", "evaluación"],
    ["aula", "aulas", "class", "lesson", "clase", "lección"],
    ["curso", "cursos", "course", "courses", "curso"],
    ["matrícula", "matricula", "enrollment", "matrícula", "inscripción"],
    ["tcc", "trabalho de conclusão", "trabalho de conclusao", "thesis", "tesis"],
    ["defesa", "defesa de tese", "defesa de dissertação", "thesis defense", "defensa de tesis"],
    ["apresentação de tcc", "apresentacao de tcc", "tcc presentation"],
    ["entrega de trabalho", "assignment submission", "entrega de trabajo"],
    ["prazo de matrícula", "enrollment deadline", "plazo de matrícula"],
    ["vestibular", "enem", "exame nacional", "university entrance"],
    ["concurso", "concurso público", "concurso publico", "civil service exam"],
    ["prova de ordem", "bar exam", "examen de la barra"],
    ["dissertação", "dissertacao", "dissertation", "tesis"],
    ["monografia", "monograph", "monografía"],
    ["seminário de curso", "seminario de curso", "course seminar"],
    ["seminário de pesquisa", "research seminar"],
    ["banca", "banca examinadora", "thesis committee"],
    ["qualificação", "qualificacao", "qualifying exam"],
    ["exame de proficiência", "proficiency exam", "examen de proficiencia"],
    ["toefl", "ielts", "cambridge", "certificação de idioma"],
    ["aula de idioma", "language class", "clase de idiomas"],
    ["aula de inglês", "aula de ingles", "english class", "clase de inglés"],
    ["aula de espanhol", "spanish class", "clase de español"],
    ["aula de condução", "aula de direção", "aula de direcao", "driving lesson", "clase de conducir"],
    ["exame de condução", "exame de direção", "driving test", "examen de conducir"],
    ["carta de condução", "driver's license", "carnet de conducir"],
    ["formatura", "formaturas", "graduation", "graduación"],
    ["colação de grau", "colacao de grau", "graduation ceremony"],
    ["conclusão de curso", "conclusao de curso", "course completion"],
    ["entrega de documento na secretaria", "submit documents"],
    ["renovação de matrícula", "renovacao de matricula", "re-enrollment"],
    ["trancamento", "trancamento de matrícula"],
    ["abertura de turma", "class opening"],
    ["workshop acadêmico", "workshop academico", "academic workshop"],
    ["congresso acadêmico", "congresso academico", "academic conference"],
    ["apresentação de paper", "paper presentation", "presentación de artículo"],
    ["submissão de artigo", "submissao de artigo", "paper submission"],
    ["revisão de artigo", "revisao de artigo", "article review"],
    ["prazo de submissão", "submission deadline"],
    ["orientação", "orientacao", "supervision", "supervisión"],
    ["reunião de orientação", "reuniao de orientacao", "supervision meeting"],
    ["qualificação de mestrado", "master's qualifying"],
    ["qualificação de doutorado", "phd qualifying"],
    ["seminário de orientação", "supervision seminar"],
    ["inscrição em disciplina", "inscricao em disciplina", "course registration"],
    ["trabalho em grupo", "group work", "trabajo en grupo"],
    ["seminário de leitura", "reading seminar"],
    ["prova oral", "oral exam", "examen oral"],
    ["prova escrita", "written exam", "examen escrito"],
    ["recuperação", "recuperacao", "make-up exam", "recuperación"],
    ["segunda chamada", "second call", "segunda convocatoria"],
    ["nota", "grades", "notas", "calificaciones"],
    ["revisão de prova", "revisao de prova", "exam review"],
    ["recurso", "appeal", "recurso de nota"],
    ["trancamento de disciplina", "course withdrawal"],
    ["estágio", "estagio", "internship", "prácticas"],
    ["defesa de estágio", "defesa de estagio", "internship defense"],
    ["relatório de estágio", "relatorio de estagio", "internship report"],
    ["seminário de integração", "seminario de integracao", "integration seminar"],
    ["calourada", "freshman week", "semana de integración"],
    ["reunião de curso", "reuniao de curso", "course meeting"],
    ["coordenação de curso", "coordenacao de curso", "course coordination"],
    ["secretaria", "academic office", "secretaría"],
    ["biblioteca", "library", "biblioteca"],
    ["devolução de livro", "devolucao de livro", "book return"],
    ["renovação de empréstimo", "renovacao de emprestimo", "loan renewal"],
    # 281-360: Família e eventos sociais
    ["casamento", "casamentos", "wedding", "boda", "bodas"],
    ["cerimônia", "cerimonia", "ceremony", "ceremonia"],
    ["aniversário", "aniversario", "birthday", "cumpleaños"],
    ["aniversário de casamento", "anniversary", "aniversario de boda"],
    ["festa", "festas", "party", "fiesta"],
    ["formatura", "graduation party"],
    ["batizado", "baptism", "bautizo"],
    ["comunhão", "comunhao", "communion", "comunión"],
    ["bar mitzvah", "bat mitzvah"],
    ["jantar", "jantares", "dinner", "cena"],
    ["almoço", "almoco", "lunch", "almuerzo"],
    ["café da manhã", "cafe da manha", "breakfast", "desayuno"],
    ["encontro", "encontros", "meetup", "encuentro"],
    ["encontro com amigos", "meeting with friends"],
    ["reunião de família", "reuniao de familia", "family gathering", "reunión familiar"],
    ["natal", "christmas", "navidad"],
    ["ano novo", "new year", "año nuevo"],
    ["páscoa", "pascoa", "easter", "pascua"],
    ["dia das mães", "dia das maes", "mother's day", "día de la madre"],
    ["dia dos pais", "father's day", "día del padre"],
    ["dia do namorado", "valentine's", "san valentín"],
    ["despedida de solteiro", "bachelor party", "despedida de soltero"],
    ["chá de bebê", "cha de bebe", "baby shower"],
    ["chá de panela", "cha de panela", "bridal shower"],
    ["coquetel", "cocktail", "cóctel"],
    ["brunch", "brunch"],
    ["happy hour", "happy hour"],
    ["visita", "visitas", "visit", "visita"],
    ["visita aos avós", "visita aos avos", "visit grandparents"],
    ["visita ao hospital", "hospital visit"],
    ["velório", "velorio", "wake", "velatorio"],
    ["funeral", "funeral", "entierro"],
    ["memorial", "memorial service"],
    ["homenagem", "tribute", "homenaje"],
    ["inauguração", "inauguracao", "opening", "inauguración"],
    ["inauguração de casa", "housewarming"],
    ["abertura de loja", "store opening"],
    ["lançamento de produto", "lancamento de produto", "product launch"],
    ["preview", "pré-estreia", "pre-estreia", "avant-première"],
    ["estreia", "premiere", "estreno"],
    ["gala", "gala", "gala dinner"],
    ["baile", "ball", "baile"],
    ["festival", "festivals", "festival"],
    ["show", "shows", "concert", "concierto"],
    ["teatro", "theatre", "theater", "teatro"],
    ["cinema", "movie", "película"],
    ["exposição", "exposicao", "exhibition", "exposición"],
    ["museu", "museum", "museo"],
    ["galeria", "gallery", "galería"],
    ["live", "live stream", "transmissão ao vivo", "transmissao ao vivo"],
    ["webinar ao vivo", "live webinar"],
    ["transmissão", "transmissao", "broadcast"],
    ["encontro de ex-alunos", "alumni reunion"],
    ["reunião de turma", "reuniao de turma", "class reunion"],
    ["confraternização", "confraternizacao", "company party"],
    ["amigo secreto", "secret santa"],
    ["ceia", "christmas dinner", "cena de navidad"],
    ["réveillon", "reveillon", "new year's eve"],
    ["festa junina", "junina", "festa de são joão"],
    ["carnaval", "carnival", "carnaval"],
    ["desfile", "parade", "desfile"],
    ["premiação", "premiacao", "award ceremony", "premios"],
    ["entrega de prêmio", "entrega de premio", "award delivery"],
    ["abertura de evento", "event opening"],
    ["credenciamento", "registration", "acreditación"],
    ["coffee break", "pausa para café", "pausa para cafe"],
    ["networking", "networking session"],
    ["foto oficial", "official photo"],
    ["cobertura", "event coverage"],
    ["imprensa", "press", "prensa"],
    ["entrevista coletiva", "press conference"],
    ["assessoria de imprensa", "press office"],
    # 361-440: Serviços e compromissos
    ["advogado", "advogada", "lawyer", "abogado"],
    ["consulta jurídica", "legal consultation", "consulta legal"],
    ["audiência", "audiencia", "court hearing", "audiencia"],
    ["julgamento", "trial", "juicio"],
    ["depoimento", "testimony", "declaración"],
    ["assinatura de documento", "document signing", "firma de documento"],
    ["cartório", "cartorio", "notary", "notaría"],
    ["reconhecimento de firma", "signature recognition"],
    ["procuração", "procuracy", "poder notarial"],
    ["testamento", "will", "testamento"],
    ["inventário", "inventario", "probate", "inventario"],
    ["divórcio", "divorcio", "divorce", "divorcio"],
    ["contador", "accountant", "contador"],
    ["declaração ir", "declaracao ir", "tax return", "declaración de impuestos"],
    ["imposto de renda", "income tax"],
    ["abertura de empresa", "company registration"],
    ["registro de marca", "trademark registration"],
    ["contrato social", "articles of incorporation"],
    ["banco", "bank", "banco"],
    ["agência bancária", "agencia bancaria", "bank branch"],
    ["abertura de conta", "account opening"],
    ["fechamento de conta", "account closure"],
    ["empréstimo", "emprestimo", "loan", "préstamo"],
    ["renovação de empréstimo", "loan renewal"],
    ["seguro", "insurance", "seguro"],
    ["renovação de seguro", "renovacao de seguro", "insurance renewal"],
    ["sinistro", "insurance claim", "reclamo"],
    ["vistoria de seguro", "insurance inspection"],
    ["reparo", "repair", "reparación"],
    ["manutenção", "manutencao", "maintenance", "mantenimiento"],
    ["instalação", "instalacao", "installation", "instalación"],
    ["entrega de encomenda", "package delivery"],
    ["entrega de móvel", "entrega de movel", "furniture delivery"],
    ["mudança", "mudanca", "move", "mudanza"],
    ["entrega de chave", "key handover"],
    ["vistoria de imóvel", "vistoria de imovel", "property inspection"],
    ["assinar contrato de aluguel", "sign lease"],
    ["devolução de imóvel", "devolucao de imovel"],
    ["condomínio", "condominio", "condo fee"],
    ["reparo em casa", "home repair"],
    ["encanador", "plumber", "fontanero"],
    ["eletricista", "electrician", "electricista"],
    ["pintor", "painter", "pintor"],
    ["limpeza", "cleaning", "limpieza"],
    ["lavagem de carro", "car wash"],
    ["troca de óleo", "troca de oleo", "oil change"],
    ["oficina", "mechanic", "taller mecánico"],
    ["revisão do carro", "revisao do carro", "car service"],
    ["inspeção veicular", "inspecao veicular", "vehicle inspection"],
    ["retirada de documento", "document pickup"],
    ["renovação de documento", "renovacao de documento", "document renewal"],
    ["carteira de motorista", "driver's license renewal"],
    ["identidade", "id", "identity card", "documento de identidad"],
    ["certidão", "certidao", "certificate", "certificado"],
    ["atestado", "certificate", "certificado"],
    ["laudo técnico", "laudo tecnico", "technical report"],
    ["perícia", "pericia", "expertise", "peritaje"],
    ["avaliação de imóvel", "avaliacao de imovel", "property appraisal"],
    ["test drive", "test-drive", "prueba de manejo"],
    ["compra de carro", "car purchase"],
    ["assinatura de financiamento", "loan signing"],
    ["fechamento de compra", "closing"],
    ["entrega de imóvel", "property delivery"],
    ["registro de imóvel", "registro de imovel", "property registration"],
    ["escritura", "deed", "escritura"],
    ["tabelionato", "notary"],
    ["inventário extrajudicial", "out-of-court inventory"],
    ["mediação", "mediacao", "mediation", "mediación"],
    ["conciliação", "conciliacao", "conciliation"],
    ["arbitragem", "arbitration", "arbitraje"],
    ["audiência de conciliação", "conciliation hearing"],
    ["corte de cabelo", "haircut", "corte de pelo"],
    ["cabeleireiro", "hairdresser", "peluquero"],
    ["barbearia", "barbershop", "barbería"],
    ["salão", "salao", "salon", "salón"],
    ["estética", "estetica", "aesthetics", "estética"],
    ["spa", "spa", "day spa"],
    ["tatuagem", "tattoo", "tatuaje"],
    ["piercing", "piercing"],
    ["depilação a laser", "laser hair removal"],
    ["limpeza de pele", "facial cleansing"],
    ["tratamento capilar", "hair treatment"],
    ["manicure e pedicure", "manicure and pedicure"],
    ["maquiagem", "makeup", "maquillaje"],
    ["noiva", "bridal makeup"],
    ["foto", "photoshoot", "sesión de fotos"],
    ["filmagem", "filming", "grabación"],
    ["entrevista para mídia", "media interview"],
    ["podcast", "podcast recording"],
    ["gravação", "gravacao", "recording", "grabación"],
    ["dublagem", "dubbing", "doblaje"],
    # 441-500: Outros compromissos importantes
    ["coleta de exame", "coleta de exame", "lab collection"],
    ["retirada de resultado", "result pickup"],
    ["doação", "doacao", "donation", "donación"],
    ["doação de órgão", "organ donation"],
    ["transfusão", "transfusao", "transfusion"],
    ["quimioterapia", "chemotherapy"],
    ["radioterapia", "radiotherapy"],
    ["sessão de hemodiálise", "hemodialysis session"],
    ["acompanhante", "companion", "acompañante"],
    ["consulta de acompanhamento pós-cirurgia", "post-surgery follow-up"],
    ["retirada de pontos", "stitches removal"],
    ["troca de curativo", "dressing change"],
    ["aplicação de medicamento", "aplicacao de medicamento", "medication administration"],
    ["vacinação em massa", "mass vaccination"],
    ["teste de gravidez", "pregnancy test"],
    ["ultrassom obstétrico", "ultrasound"],
    ["monitoramento", "monitoramento", "monitoring"],
    ["teleconsulta", "teleconsultation"],
    ["segunda opinião médica", "second medical opinion"],
    ["autorização judicial", "autorizacao judicial", "court authorization"],
    ["custódia", "custodia", "custody"],
    ["pensão", "pensao", "alimony", "pensión"],
    ["visita monitorada", "supervised visit"],
    ["mediação familiar", "mediacao familiar"],
    ["adoção", "adocao", "adoption", "adopción"],
    ["entrega de criança", "child handover"],
    ["guarda", "custody hearing"],
    ["pensão alimentícia", "pensao alimenticia", "child support"],
    ["registro de nascimento", "birth registration"],
    ["registro de óbito", "death registration"],
    ["certidão de casamento", "marriage certificate"],
    ["naturalização", "naturalizacao", "naturalization"],
    ["cidadania", "citizenship", "ciudadanía"],
    ["refúgio", "refugio", "asylum"],
    ["autorização de trabalho", "work permit"],
    ["carteira de trabalho", "work permit"],
    ["rescisão", "termination", "rescisión"],
    ["acordo trabalhista", "labor agreement"],
    ["fgts", "withdrawal"],
    ["aposentadoria", "retirement", "jubilación"],
    ["inss", "social security"],
    ["benefício", "beneficio", "benefit", "beneficio"],
    ["perícia médica", "pericia medica", "medical examination"],
    ["recurso administrativo", "administrative appeal"],
    ["licitação", "licitacao", "bidding"],
    ["proposta em licitação", "bid proposal"],
    ["abertura de envelope", "bid opening"],
    ["sessão pública", "sessao publica", "public session"],
    ["concurso público", "public tender"],
    ["prova de concurso", "civil service exam"],
    ["nomeação", "nomeacao", "appointment"],
    ["posse", "taking office"],
    ["sindicância", "sindicancia", "investigation"],
    ["processo administrativo", "administrative proceeding"],
    ["recurso hierárquico", "hierarchical appeal"],
    ["mandado de segurança", "writ of mandamus"],
    ["ação judicial", "acao judicial", "lawsuit"],
    ["citação", "citacao", "summons"],
    ["intimação", "intimacao", "subpoena"],
    ["contestação", "contestacao", "answer"],
    ["audiência de instrução", "evidentiary hearing"],
    ["sentença", "sentenca", "judgment"],
    ["recurso", "appeal"],
    ["execução", "execucao", "enforcement"],
    ["penhora", "attachment"],
    ["leilão", "leilao", "auction"],
    ["desocupação", "desocupacao", "eviction"],
    ["despejo", "eviction"],
    ["conciliação trabalhista", "labor conciliation"],
    ["reclamação trabalhista", "reclamacao trabalhista", "labor claim"],
    ["acordo extrajudicial", "out-of-court settlement"],
    ["transação", "transacao", "settlement"],
    ["mediação judicial", "court mediation"],
    ["conciliação judicial", "court conciliation"],
    ["arbitragem internacional", "international arbitration"],
    ["laudo arbitral", "arbitral award"],
    ["homologação", "homologacao", "ratification"],
    ["desistência", "desistencia", "withdrawal"],
    ["renúncia", "renuncia", "waiver"],
    ["quitação", "quitacao", "release"],
    ["encerramento de contrato", "contract closure"],
    ["rescisão contratual", "contract termination"],
    ["renovação de contrato", "renovacao de contrato", "contract renewal"],
    ["aditivo", "amendment", "aditivo contractual"],
    ["assinatura de aditivo", "amendment signing"],
    ["consulta de rotina cardiologia", "cardiology checkup", "revisão cardíaca"],
    ["ecocardiograma", "echocardiogram", "ecocardiografía"],
    ["holter", "holter monitor", "monitor holter"],
    ["cateterismo", "catheterization", "cateterismo"],
    ["angioplastia", "angioplasty", "angioplastia"],
    ["mamografia", "mammography", "mamografía"],
    ["colonoscopia", "colonoscopy", "colonoscopia"],
    ["endoscopia", "endoscopy", "endoscopia"],
]


def _build_keyword_set() -> frozenset[str]:
    """Constrói o set de todas as keywords (lowercase) para matching rápido."""
    all_kw: set[str] = set()
    for group in PROACTIVE_NUDGE_EVENT_KEYWORDS:
        for kw in group:
            if kw and kw.strip():
                all_kw.add(kw.strip().lower())
    return frozenset(all_kw)


_PROACTIVE_NUDGE_KEYWORDS_SET: frozenset[str] | None = None


def is_important_event_for_proactive_nudge(event_name: str) -> bool:
    """
    True se o nome do evento (ex.: "consulta no dentista") corresponde a algum
    evento considerado importante para o nudge proativo 12h antes.
    """
    if not event_name or not (event_name or "").strip():
        return False
    global _PROACTIVE_NUDGE_KEYWORDS_SET
    if _PROACTIVE_NUDGE_KEYWORDS_SET is None:
        _PROACTIVE_NUDGE_KEYWORDS_SET = _build_keyword_set()
    text = (event_name or "").strip().lower()
    # Verificar se alguma keyword está contida no texto do evento
    return any(kw in text for kw in _PROACTIVE_NUDGE_KEYWORDS_SET)


def count_proactive_nudge_events() -> int:
    """Número de grupos de eventos na lista (para documentação)."""
    return len(PROACTIVE_NUDGE_EVENT_KEYWORDS)
